### ISSUE TITLE
variableSizeWithEndOfBlockMarker*

### ISSUE THREAD

**Issue by sirinath** [scodec/scodec#65]
Sometimes when dealing with variable size encodings we might not know the size but there will be a end of block marker. Hence is it possible to add the above where we can get the end of the decoding when a delimiter is encountered. In this scheme you have to consider how to escape if encoded stream can have the delimiter as part of the legal encoding. You should be able supply some of the common conventions.

**Comment by sirinath** [comment]
In addition maybe it would be good to have minimum and maximum length parameters.

**Comment by sirinath** [comment]
E.g.

 - FIX - uses SOH control signal to specify is a Tag=Value has ended
 - SMTP uses a single "." in a new line

You have to specify if if the delimiter is par of the next value of the last read value. in FIX it is part of the last value, hence this can be cleared when encounderted. If it part of the next value then you have to leave it in the stream.

**Comment by mpilquist** [comment]
Do you have a suggested signature for `variableSizeWithEndOfBlockMarker`? The various attempts I've made all feel too specific to any given protocol.

**Comment by sirinath** [comment]
```
variableSizeBitsWithBlockMarker[A](start: Codec[A], end: Codec[A], value: Codec[A], includeStartMarker: Boolean = false, includeEndMarker: Boolean = false, escape: Seq[Codec[A]] =  Seq.empty[Codec[A]]): Codec[A]

variableSizeBitsWithEndOfBlockMarker[A](end: Codec[A], value: Codec[A], includeMarker: Boolean = false, escape: Seq[Codec[A]] =  Seq.empty[Codec[A]]): Codec[A]

variableSizeBitsWithStartOfBlockMarker[A](start: Codec[A], value: Codec[A], includeMarker: Boolean = false, escape: Seq[Codec[A]] =  Seq.empty[Codec[A]]): Codec[A]

variableSizeBitsWithBlockSeperatorMarker[A](marker: Codec[A], value: Codec[A], includeMarker: Boolean = false, markerAssociatedWithStart: Boolean = false, escape: Seq[Codec[A]] =  Seq.empty[Codec[A]]): Codec[A]
```

**Comment by mpilquist** [comment]
I feel that these signatures are not a good fit for the core library, at least at this point. I say that because it is fairly hard to understand what the bit pattern is based on the signature. Also, I suspect it would be easier for folks to handle bit patterns that adhere to this structure on an as-needed basis, even if these methods existed in the core library. That is, it would be simpler to create a custom codec or combinator that does exactly what is necessary rather than trying to use these generalized combinators.

If other folks disagree, feel free to comment, but I'm going to close this one for now.

Cheers
